name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'



  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: |
          echo Build started
          npm run build
          echo Build finished

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          echo Publish started
          npm run publish
          echo Publish finished

