name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  second-job:
    runs-on: ${{ needs.first-job.runs-on }}

    steps:
      - name: Second job on the same runner
        run: echo "This is the second job running on the same runner as the first job"

  third-job:
    runs-on: ${{ needs.first-job.runs-on }}

    steps:
      - name: Third job on the same runner
        run: echo "This is the third job running on the same runner as the first job"
In this configuration:


