name: CI

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  
  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Update package.json with tag version
        run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/}"
          TAG_NAME=${GITHUB_REF#refs/tags/}
          jq --arg tag_version "$TAG_VERSION" '.version = $new_version' package.json > temp.json && mv temp.json package.json

      - name: Install dependencies
        run: npm install  
      
      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}



